# Basic
title: "Haneen Najjar"
name: "Haneen Najjar"
description: "Trustworthy ML • Adversarial Robustness • Fairness • Security | Tel Aviv University"
locale: "en-US"

# IMPORTANT: this must match your GitHub Pages domain
url: "https://haneenn24.github.io"

baseurl: ""

# Theme (Academic Pages / Minimal Mistakes)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Author (left sidebar)
author:
  name: "Haneen Najjar"
  avatar: "images/profile.jpg"
  bio: "Researcher & applied ML engineer focusing on fair adversarial robustness, security-critical ML, and trustworthy computer vision."
  email: "haneennaj24@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:haneennaj24@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/haneen-najjar2494"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/haneenn24"
    - label: "arXiv"
      icon: "ai ai-arxiv"
      url: "https://arxiv.org/abs/2509.12939"

# Plugins allowed by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Navigation (top menu)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages

# Build settings
markdown: kramdown
permalink: /:categories/:title/
timezone: "Asia/Jerusalem"
